export const demoEvents = [
  {
    id: "evt-comedy-1",
    title: "Bangalore LOL Nights",
    city: "Bengaluru",
    category: "Comedy",
    venue: "Indiranagar Social",
    price: 499,
    cover: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d",
    date: "2024-08-15T19:30:00+05:30",
    seats: 120,
    booked: 64,
    tags: ["standup", "english"],
    description: "A curated lineup of the sharpest comics in town with honest pricing and transparent fees.",
    refundPolicy: "Organizer approval required; cut-off 6 hours before start",
    perks: ["Seat map with fair-queue", "Smart Split links", "Pay later balance if friends drop"] as const,
  },
  {
    id: "evt-music-1",
    title: "Indie Folk Evenings",
    city: "Mumbai",
    category: "Music",
    venue: "Bandstand Amphitheatre",
    price: 699,
    cover: "https://images.unsplash.com/photo-1489515217757-5fd1be406fef",
    date: "2024-08-20T20:00:00+05:30",
    seats: 300,
    booked: 210,
    tags: ["folk", "hindi"],
    description: "Soulful indie artists with beachside breeze and clear ticket math.",
    refundPolicy: "Free cancellations till 24 hours; organizer decides post cut-off",
    perks: ["Merch counter fast-lane", "Offline QR for beachside"] as const,
  },
  {
    id: "evt-workshop-1",
    title: "Storytelling for Creators",
    city: "Delhi NCR",
    category: "Workshop",
    venue: "Hauz Khas Studio",
    price: 950,
    cover: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?sig=2",
    date: "2024-08-28T11:00:00+05:30",
    seats: 60,
    booked: 22,
    tags: ["content", "creator", "hindi"],
    description: "Hands-on assignments, breakout rooms, and peer review for creators who want to ship weekly.",
    refundPolicy: "No-shows converted to credits; full refund if waitlist takes your seat",
    perks: ["Downloadable workbook", "Peer review group invites", "Lead mentor AMA"] as const,
  },
  {
    id: "evt-food-1",
    title: "Hyderabadi Biryani Trail",
    city: "Hyderabad",
    category: "Food & Culture",
    venue: "Charminar Meeting Point",
    price: 849,
    cover: "https://images.unsplash.com/photo-1521017432531-fbd92d768814",
    date: "2024-08-18T17:00:00+05:30",
    seats: 40,
    booked: 33,
    tags: ["food", "heritage"],
    description: "Guided walk through Irani cafés, spice bazaars, and a live haleem counter with transparent tasting slabs.",
    refundPolicy: "100% refundable if rain; partial refunds after organizer nod",
    perks: ["2-hour guided trail", "Unlimited chai ", "Offline ticket for checkpoints"] as const,
  },
];

export const demoBookings = [
  {
    id: "bkg-123",
    eventId: "evt-comedy-1",
    status: "CONFIRMED" as const,
    tickets: 2,
    ticketPrice: 499,
    smartSplitLinks: ["https://pay.indietix.test/share/a", "https://pay.indietix.test/share/b"],
    paymentStatus: "PAID",
    offlineReady: true,
    refundStatus: "NOT_REQUESTED" as const,
    checkInStatus: "PENDING" as const,
    fees: {
      paymentGatewayFee: 10,
      serverMaintenanceFee: 5,
      platformFixedFee: 10,
      platformPercentFee: 0.05,
    },
  },
  {
    id: "bkg-456",
    eventId: "evt-music-1",
    status: "REFUND_PENDING" as const,
    tickets: 3,
    ticketPrice: 699,
    smartSplitLinks: ["https://pay.indietix.test/share/c"],
    paymentStatus: "PARTIAL", // awaiting friends
    offlineReady: false,
    refundStatus: "AWAITING_ORGANIZER" as const,
    checkInStatus: "NOT_APPLICABLE" as const,
    fees: {
      paymentGatewayFee: 12,
      serverMaintenanceFee: 5,
      platformFixedFee: 10,
      platformPercentFee: 0.05,
    },
  },
];

export const demoAttendees = [
  {
    id: "att-1",
    eventId: "evt-comedy-1",
    name: "Aditi",
    ticketType: "Regular",
    status: "CONFIRMED",
    checkIn: "Not checked-in",
    offlineTicket: true,
  },
  {
    id: "att-2",
    eventId: "evt-comedy-1",
    name: "Rohan",
    ticketType: "Regular",
    status: "CONFIRMED",
    checkIn: "Checked-in",
    offlineTicket: true,
  },
  {
    id: "att-3",
    eventId: "evt-music-1",
    name: "Meera",
    ticketType: "Fan Early Access",
    status: "REFUND_PENDING",
    checkIn: "Auto lock until refund decision",
    offlineTicket: false,
  },
  {
    id: "att-4",
    eventId: "evt-food-1",
    name: "Pranav",
    ticketType: "Trail Buddy",
    status: "CONFIRMED",
    checkIn: "QR generated offline",
    offlineTicket: true,
  },
];
